### ISSUE TITLE
Test whether it works on Windows

### ISSUE THREAD

**Issue by lukasmartinelli** [lukasmartinelli/postgis-editor#6]
I have no idea whether the release actually works on Windows 64bit.

**Comment by baditaflorin** [comment]
It works on windows 7 64 bits.

**Comment by nadnerb33** [comment]
v1.2.1 doesn't work for me on Win Server 2008 or Win7 (both 64bit)
When run, a window appears with a dark grey background and nothing else.
Any ideas?

**Comment by lukasmartinelli** [comment]
> v1.2.1 doesn't work for me on Win Server 2008 or Win7 (both 64bit)
> When run, a window appears with a dark grey background and nothing else.
> Any ideas?

Hmmm not really. Perhaps it has to do with the way Appveyor CI builds it?
In the end it Electron under the hood but I could not find any issues doing a quick search that Electron has Windows 7 problem.

I am sorry that I probably can not help here because I am unable to replicate the issue without setting up Windows 😁

**Comment by nadnerb33** [comment]
Thanks for the reply.
I've now unzipped directly to the root of C:\ and it is working. 
Perhaps there were permissions issues on the directory I was using before.
